# fly.toml app configuration file generated for djangoxyz on 2024-08-23T01:55:42-07:00
app = 'djangoxyz'
primary_region = 'sjc'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  DATABASE_URL = 'your-database-url'  # Ensure this is set
  SECRET_KEY = 'your-secret-key'      # Use a real secret key in production

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'
